name: CI

on:
  workflow_dispatch: # Enable manual trigger to run workflow.
  push:
    branches:
      - main
    paths:
      - '**'
      - '!CHANGELOG.md'
      - '!README.md'
      - '!LICENSE'
  pull_request:
    branches:
      - main

jobs:
  build-snapshot:
    name: Build snapshot
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    env:
      branchName: ${{github.head_ref || github.ref_name}}
      mavenOpts: >
        --no-transfer-progress
        --batch-mode
        -Dmaven.test.failure.ignore=true
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-username: GITHUB_USERNAME
          server-password: GITHUB_PAT

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up build environment
        id: setup-build-env
        run: |
          if [[ ${GITHUB_EVENT_NAME} == "workflow_dispatch" ]]; then
            echo "Build triggered manually by ${GITHUB_ACTOR}"
          else
            echo "Build triggered by commit from $(git log -1 --pretty=format:%an .) ($(git log -1 --pretty=format:%ae .))"
          fi          
          
          isMainBranch=${{env.branchName == 'main' }}        
          echo "Building from main branch: ${isMainBranch}"
          mvn -v
          
          echo "Smoke testing Maven environment and POM"        
          mvn ${mavenOpts} -f ./pom.xml -q help:evaluate -Dexpression=project.artifactId -DforceStdout
          
          artifactId=$(mvn ${mavenOpts} -f ./pom.xml -q help:evaluate -Dexpression=project.artifactId -DforceStdout)
          snapshotVersion=$(mvn ${mavenOpts} -f ./pom.xml -q help:evaluate -Dexpression=project.version -DforceStdout)
          echo "Maven artifact $artifactId snapshot version is $snapshotVersion"
        env:
          GITHUB_USERNAME: ${{github.actor}}
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}

      - name: Maven build, analyze and test artifact
        run: |
          mvn ${mavenOpts} -f ./pom.xml verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_USERNAME: ${{github.actor}}
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Locate test results
        id: locate-test-results
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "./**/surefire-reports/TEST-*.xml"

      - name: Publish test results
        if: ${{steps.locate-test-results.outputs.files_exists == 'true' && (success() || failure())}}
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
        with:
          name: JUnit test reports
          working-directory: .
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
          fail-on-error: true

      - name: Publish test coverage
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          format: jacoco
          base-path: src/main/java
